import { ArrowLeft, Blocks, Check, Power, RefreshCw, Trash2, Wrench } from "lucide-react";
import { useCallback, useState, type FormEvent } from "react";
import type { McpInstallationView, McpTestRecord } from "@kindergarten/contracts";
import { controlApi } from "../api/control-api.js";
import { ErrorState, LoadingState } from "./LoadState.js";
import { ProductNav } from "./ProductNav.js";
import { useResource } from "./use-resource.js";

export function McpPage({ mcpId }: { mcpId?: string }) {
  const load = useCallback(async () => {
    if (!mcpId) return undefined;
    return (await controlApi.mcps()).find((item) => item.mcpInstallationId === mcpId);
  }, [mcpId]);
  const { state, retry } = useResource(load);
  return <main className="product-page"><ProductNav active="me" />{!mcpId ? <McpCreate /> : state.phase === "loading" ? <LoadingState label="正在读取 MCP" /> : state.phase === "error" ? <ErrorState {...state} retry={retry} /> : state.data ? <McpDetail value={state.data} retry={retry} /> : <div className="product-state"><strong>MCP 不存在</strong><a href="/me?tab=mcps">返回</a></div>}</main>;
}

function McpCreate() {
  const [name, setName] = useState(""); const [url, setUrl] = useState("");
  const [test, setTest] = useState<McpTestRecord | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function testConnection(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const value = await controlApi.testMcp({ name: name.trim(), transport: "streamable_http", url: url.trim(), auth: { kind: "none" } }); setTest(value); if (value.state === "failed") setMessage(value.error?.message ?? "连接失败"); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); setTest(null); } finally { setBusy(false); } }
  async function install() { if (!test || test.state !== "succeeded") return; setBusy(true); try { await controlApi.installMcp(test.testId, name.trim()); location.href = "/me?tab=mcps"; } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); setBusy(false); } }
  return <div className="product-editor-shell"><header className="product-page-heading"><a href="/me?tab=mcps"><ArrowLeft size={16} /></a><div><span>ADMIN · REMOTE MCP</span><h1>添加远程 MCP</h1><p>首版只支持无需鉴权的 Streamable HTTP；Bearer Token 与小说 MCP 均留白。</p></div></header><div className="product-mcp-layout"><form className="product-form" onSubmit={testConnection}><section><header><Blocks size={16} /><div><strong>连接配置</strong><small>先测试，再安装</small></div></header><label><span>MCP 名称</span><input required value={name} onChange={(event) => { setName(event.target.value); setTest(null); }} /></label><label><span>Streamable HTTP 地址</span><input required inputMode="url" placeholder="https://example.com/mcp" value={url} onChange={(event) => { setUrl(event.target.value); setTest(null); }} /></label><label><span>认证</span><input disabled value="无需认证（none）" /></label></section><footer><span>{message || (test?.state === "succeeded" ? "连接验证通过，可以安装。" : "测试会执行 initialize 与能力发现。")}</span><button disabled={busy} type="submit"><RefreshCw size={14} />{busy ? "测试中" : "测试连接"}</button><button disabled={busy || test?.state !== "succeeded"} type="button" onClick={() => void install()}><Check size={14} />确认安装</button></footer></form><aside className="product-discovery"><header><strong>能力发现</strong><small>真实连接快照</small></header>{!test ? <div className="product-state"><Blocks size={20} /><p>等待测试连接。</p></div> : test.state === "failed" ? <div className="product-state error"><strong>连接失败</strong><p>{test.error?.message}</p></div> : <CapabilityList snapshot={test.snapshot} />}</aside></div></div>;
}

function McpDetail({ value, retry }: { value: McpInstallationView; retry: () => void }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function action(name: "enable" | "disable" | "reconnect") { setBusy(true); setMessage(""); try { await controlApi.mcpAction(value.mcpInstallationId, name); retry(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function remove() { if (value.deletable !== true || !confirm(`卸载 ${value.name}？服务端会重新计算并移除当前 Agent 绑定。`)) return; setBusy(true); try { await controlApi.removeMcp(value.mcpInstallationId); location.href = "/me?tab=mcps"; } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); setBusy(false); } }
  return <div className="product-editor-shell"><header className="product-page-heading"><a href="/me?tab=mcps"><ArrowLeft size={16} /></a><div><span>ADMIN · REMOTE MCP</span><h1>{value.name}</h1><p>{value.url}</p></div></header><section className="product-detail-card"><header><div><Blocks size={18} /><span><strong>{value.name}</strong><small>Streamable HTTP · auth {value.authKind}</small></span></div><em>{value.state}</em></header><dl><div><dt>地址</dt><dd>{value.url}</dd></div><div><dt>状态</dt><dd>{value.state}</dd></div><div><dt>能力版本</dt><dd>{value.snapshot?.generation ?? 0}</dd></div><div><dt>最近连接</dt><dd>{value.lastConnectedAt ?? "尚未连接"}</dd></div></dl><div className="product-detail-actions"><button disabled={busy} type="button" onClick={() => void action("reconnect")}><RefreshCw size={13} />重新连接</button><button disabled={busy} type="button" onClick={() => void action(value.enabled ? "disable" : "enable")}><Power size={13} />{value.enabled ? "停用" : "启用"}</button>{value.deletable === true && <button className="danger" disabled={busy} type="button" onClick={() => void remove()}><Trash2 size={13} />卸载</button>}</div>{message && <p className="product-error-text">{message}</p>}</section><section className="product-panel"><header><div><strong>已发现能力</strong><small>重新连接会刷新这一快照</small></div></header><CapabilityList snapshot={value.snapshot} /></section></div>;
}
function CapabilityList({ snapshot }: { snapshot?: McpInstallationView["snapshot"] }) { if (!snapshot) return <div className="product-empty">没有可用快照</div>; return <div className="product-capability-list"><section><strong>Tools · {snapshot.tools.length}</strong>{snapshot.tools.map((item) => <article key={item.name}><Wrench size={12} /><span><strong>{item.name}</strong><small>{item.description ?? "无说明"}</small></span></article>)}</section><section><strong>Resources · {snapshot.resources.length}</strong>{snapshot.resources.map((item) => <article key={item.uri}><Blocks size={12} /><span><strong>{item.name ?? item.uri}</strong><small>{item.uri}</small></span></article>)}</section><section><strong>Prompts · {snapshot.prompts.length}</strong>{snapshot.prompts.map((item) => <article key={item.name}><Blocks size={12} /><span><strong>{item.name}</strong><small>{item.description ?? "无说明"}</small></span></article>)}</section></div>; }
